services:
  - type: web
    name: feminine-aura-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --no-input
    startCommand: gunicorn feminine_aura.wsgi:application
    healthCheckPath: /api/site-status/
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.0"