# Generated by Django 6.1.1 on 2026-09-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetsetup',
            name='savings_pct',
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='savings',
        ),
        migrations.AddField(
            model_name='budgetsetup',
            name='savings_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetsetup',
            name='wants_pct',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
    ]
