# Generated by Django 6.1.1 on 2026-09-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_budgetsetup_savings_pct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetsetup',
            name='essentials_pct',
        ),
        migrations.RemoveField(
            model_name='budgetsetup',
            name='wants_pct',
        ),
        migrations.AlterField(
            model_name='budgetsetup',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Optional. Used only for % context.', max_digits=12),
        ),
    ]
