# Generated by Django 6.1.1 on 2026-09-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_live', models.BooleanField(default=False, help_text='When OFF, visitors see the Coming Soon page. Admins always see the real site.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Status',
                'verbose_name_plural': 'Site Status',
            },
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-created_at']},
        ),
    ]
