# Generated by Django 5.2.17 on 2026-09-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_sitestatus_alter_subscriber_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_paid',
            field=models.BooleanField(default=False, help_text='True once the user has paid for budget tracker access.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
